adding missing dependency on Markdown and somehow strange dependency on importlib - without it we get an error
 Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/tmp/pip-build-9uPv6g/apbvt/setup.py", line 86, in <module>
        'console_scripts': ['apbvt = apbvt.bvt:main']
      File "/usr/lib64/python2.6/distutils/core.py", line 113, in setup
        _setup_distribution = dist = klass(attrs)
      ...
      File "build/bdist.linux-x86_64/egg/odintools/args.py", line 1, in <module>
      File "build/bdist.linux-x86_64/egg/odintools/commands.py", line 5, in <module>
        import commands
      File "/root/testenv/lib/python2.6/site-packages/markdown/__init__.py", line 40, in <module>
        import importlib
    ImportError: No module named importlib

during markdown usage - likely it means that markdown didn't define its dependencies properly.